---
image: alpine:3.12

static-analysis:
  image: alpine:3.8
  before_script:
    - apk add cppcheck
  script:
    - test/static_analysis.sh

build::amd64:
  before_script:
    - apk add build-base linux-headers sdl2-dev sdl2_ttf-dev cryptsetup-dev
  script:
    - make
  artifacts:
    paths:
      - bin/
