---
image: alpine:3.8

stages:
  - test
  - build

static-analysis:
  stage: test
  before_script:
    - apk add cppcheck
  script:
    - test/static_analysis.sh

build::amd64:
  stage: build
  before_script:
    - apk add build-base linux-headers sdl2-dev sdl2_ttf-dev cryptsetup-dev
  script:
    - make
  artifacts:
    paths:
      - bin/
